---
# Source: renovate/charts/renovate/charts/redis/templates/master/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: renovate-redis-master
  namespace: "renovate"
  labels:
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 8.2.1
    helm.sh/chart: redis-22.0.7
